### PR TITLE
fix: altered no nsdoc file warning message

### LINKED ISSUE #275: Warning instead of Error in case of no NSDoc files are found; More descriptive warning message
When no NSDoc files are found, [a log Event and a snackbar are shown in the frontend.](https://github.com/com-pas/compas-open-scd/blob/main/packages/compas-open-scd/src/compas/CompasNsdoc.ts#L43)

The snackbar should be removed.
We should check with openscd if we want to divide logging an Error and showing the Snackbar in the bottom into 2 seperate things or that we want to add a flag to the event to skip showing the snackbar

### PR DESCRIPTION
**Pull request by Stef3st**
closes #275

### CODE REVIEW

File: packages/compas-open-scd/src/translations/en.ts [hunk 1]
```diff
@@ -871,6 +871,10 @@ export const en = {
       server: 'Error communicating with CoMPAS Ecosystem',
       serverDetails: '{{type}}: {{message}}',
     },
+    warning: {
+      nsdoc: 'Process NSD loading error',
```
Comment (Sander3003) [inline packages/compas-open-scd/src/translations/en.ts:875]: Is it applicable to all NSD files or NSdoc files only?
Possible: "Could not load NSdoc files, not files available on the server."

Comment (Stef3st) [reply packages/compas-open-scd/src/translations/en.ts:875]: NSdoc files only. I got the title out of the issue. I think what you suggest might be a bit long for a log title. Maybe just `Could not load NSdoc file`?

**Review by juancho0202 — APPROVED** [review]
